import { Inter } from "next/font/google";
import Cursor from "@/cursorcomp/Cursor";
import "./globals.css";

import Menu from "@/components/menu/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Toms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}> 

        
        <Menu /> 
        <Cursor/>
        {children}
      </body>
    </html>
  );
}
